### ISSUE TITLE
display current and previous ICY information

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/yamlradio#3]
feature request: instead of overwriting the ICY info on update, display and update the previous as well as the current info

Radio1 for example typically alternates the streamtitle with name of the current song with the name of the radio show. This implies the name of the current song is periodically invisible...

wanted:

```
Speelt nu af: [Radio 1 (België)]
Info:         [Monschau]                                                        
Info:         [ARTIST - song]
```

**Comment by GijsTimmers** [comment]
Hi, thank you for taking the effort to write this issue.

There are things to consider here:
- Without a pinch of `ncurses` magic, the Python cursor won't go "one line up".
- Some radio stations don't alternate two messages, but rather three. Or only one. For example, Radio 538 only shows the current playing song. Showing two messages would then mean that the last message, which is irrelevant by now, would be shown as well.

Some possible solutions:
- Try to show multiple messages
  - Show both the old and the new ICY message on one line. Apart from the problem of the possibility of having more than two alternating ICY messages, the ICY message in itself can be quite long and need a whole line by itself. Of course, we can slice up the strings, but with such short strings (max 40 characters in default terminal width), this kind of loses its use.
  - Show an info 'ticker': both the last message and the current message will be shown on one line. If the total string length exceeds the terminal width, it will start 'rolling' over the screen. This should probably be used in conjuncture with the next bullet:
  - Edit `zenders.yaml`: for each channel, add a key, `EAIM`: Expected Alternating ICY Messages. If it's not defined, default to 1. If it's 2, cycle over the last two messages. If it's 3, cycle over the last three messages.
- Revert to the old behaviour: just print a newline after each different ICY message
- Something totally different: Alllow users to write custom — ugh — communicators for every radio station in a different file or directory. The communicators hook into their abbreviation name: that means, if `r1be` is played, automatically use the `r1beCommunicator()` if available. The custom communicators 'know what to expect' from the radio station and thus show you the information in the best way possible. If there's no custom communicator available, revert to the default one.

My preference is one of the following:
- `wontfix`: nice because it keeps the codebase small and easy
- Revert to old behaviour: for the reasons mentioned above
- Custom communicators: requires a bit more work but can give a very nice result if done properly.

At all times, I'd prefer to keep the command-line options as minimal as possible, as is the case now.

**Comment by jovanbulck** [comment]
nice ideas :D follow up:

what about allowing a user to specify the filepath to a custom communicator as an optional option for a radio station in the yaml file?

this would allow for lots of opportunities, I think

**Comment by GijsTimmers** [comment]
Absolutely, that sounds like a great idea to make this modular yet small.

**Comment by GijsTimmers** [comment]
By the way, instead of writing the (relative) path in the yaml file, wouldn't it be easier to just create a directory, `communicators/`, where all the communicators go? In this directory, you can put communicators like this:

```
.
└── communicators
    ├── 538.py
    ├── r1be.py
    └── stubru.py
```

IMO, this would be cleaner than writing down the path. Thoughts?

**Comment by jovanbulck** [comment]
yes clean indeed

**Comment by GijsTimmers** [comment]
Fixed. dee50a5e31d69e678722dbf1a442ffb1c48e65d2

**Comment by GijsTimmers** [comment]
@jovanbulck: this may be of interest: http://stackoverflow.com/questions/18248142/what-can-i-use-to-go-one-line-break-back-in-a-terminal-in-python
